### ISSUE TITLE
ABOUT US: WELCOME TO G.E.Ms

### ISSUE THREAD

**Issue by TravisWadeWilliamson** [hoangle4/trans4mationNow#17]
in this text: TransformationNow is a faith-based, non-profit organization that offers a program called “G.E.M.S” GRAND Mother’s, GRAND Fathers and GRAND Mentor’s Educating Mind’s. 

Remove all the 's. Should be GRAND Mothers, GRAND Fathers and GRAND Mentors Educating Minds.

**Comment by hoangle4** [comment]
done
